### ISSUE TITLE
cmake flags duplicated

### ISSUE THREAD

**Issue by aajtodd** [awslabs/aws-crt-builder#90]
looks like cmake args are getting duplicated, unsure if this is coming from crt-builder or somewhere else. If it is from builder we should attempt to dedupe This isn't necessarily a problem right now as the flags all match (and all of the crt projects build obviously) but something we ought to address.

This is from a recent aws-c-http CI build:
```
cmake -Bbuild/aws-c-http -H. -DCMAKE_INSTALL_PREFIX=/root/aws-c-http/build/install 
-DCMAKE_PREFIX_PATH=/root/aws-c-http/build/install 
-DCMAKE_EXPORT_COMPILE_COMMANDS=ON 
-DCMAKE_BUILD_TYPE=RelWithDebInfo 
-DBUILD_TESTING=ON -DCMAKE_C_COMPILER=/usr/bin/gcc-8 -DCMAKE_CXX_COMPILER=/usr/bin/g++-8 
-DENABLE_SANITIZERS=ON -DPERFORM_HEADER_CHECK=ON 
-DLibCrypto_INCLUDE_DIR=build/deps/libcrypto/include 
-DLibCrypto_SHARED_LIBRARY=build/deps/libcrypto/lib/libcrypto.so 
-DLibCrypto_STATIC_LIBRARY=build/deps/libcrypto/lib/libcrypto.a 
-DENABLE_SANITIZERS=ON -DPERFORM_HEADER_CHECK=ON 
-DLibCrypto_INCLUDE_DIR=build/deps/libcrypto/include 
-DLibCrypto_SHARED_LIBRARY=build/deps/libcrypto/lib/libcrypto.so 
-DLibCrypto_STATIC_LIBRARY=build/deps/libcrypto/lib/libcrypto.a 
-DENABLE_SANITIZERS=ON -DPERFORM_HEADER_CHECK=ON 
-DENABLE_SANITIZERS=ON -DPERFORM_HEADER_CHECK=ON 
-DENABLE_SANITIZERS=ON -DPERFORM_HEADER_CHECK=ON 
-DENABLE_SANITIZERS=ON -DPERFORM_HEADER_CHECK=ON 
-DENABLE_SANITIZERS=ON -DPERFORM_HEADER_CHECK=ON 
-DENABLE_SANITIZERS=ON -DPERFORM_HEADER_CHECK=ON
```

**Comment by yasminetalby** [comment]
Hello @aajtodd ,

My apologies for the very long delay of answer on this issue. I am personally not able to replicate the issue with the latest version of aws-c-http. 

I will close this issue for now as it might have been fixed in since the issue submission.

If you are still experiencing this with the latest version please let me know so we can reopen the issue and work together on investigating the behavior.

Best regards,

Yasmine
